// <auto-generated />
using System;
using Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(StockDbContext))]
    partial class StockDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain_.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("PersonName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("StockId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("StockId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Domain_.Entities.Stock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Stocks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Vianet",
                            Price = 50m
                        },
                        new
                        {
                            Id = 2,
                            Name = "Agritek",
                            Price = 12m
                        },
                        new
                        {
                            Id = 3,
                            Name = "Akamai",
                            Price = 45m
                        },
                        new
                        {
                            Id = 4,
                            Name = "Baidu",
                            Price = 35m
                        },
                        new
                        {
                            Id = 5,
                            Name = "Blinkx",
                            Price = 78m
                        },
                        new
                        {
                            Id = 6,
                            Name = "Blucora",
                            Price = 94m
                        },
                        new
                        {
                            Id = 7,
                            Name = "Boingo",
                            Price = 10m
                        },
                        new
                        {
                            Id = 8,
                            Name = "Brainybrawn",
                            Price = 85m
                        },
                        new
                        {
                            Id = 9,
                            Name = "Carbonite",
                            Price = 10m
                        },
                        new
                        {
                            Id = 10,
                            Name = "China Finance",
                            Price = 2m
                        },
                        new
                        {
                            Id = 11,
                            Name = "ChinaCache",
                            Price = 89m
                        },
                        new
                        {
                            Id = 12,
                            Name = "ADR",
                            Price = 100m
                        },
                        new
                        {
                            Id = 13,
                            Name = "ChitrChatr",
                            Price = 99m
                        },
                        new
                        {
                            Id = 14,
                            Name = "Cnova",
                            Price = 12m
                        },
                        new
                        {
                            Id = 15,
                            Name = "Cogent",
                            Price = 61m
                        },
                        new
                        {
                            Id = 16,
                            Name = "Crexendo",
                            Price = 21m
                        },
                        new
                        {
                            Id = 17,
                            Name = "CrowdGather",
                            Price = 23m
                        },
                        new
                        {
                            Id = 18,
                            Name = "EarthLink",
                            Price = 18m
                        },
                        new
                        {
                            Id = 19,
                            Name = "Eastern",
                            Price = 19m
                        },
                        new
                        {
                            Id = 20,
                            Name = "ENDEXX",
                            Price = 74m
                        },
                        new
                        {
                            Id = 21,
                            Name = "Envestnet",
                            Price = 7m
                        },
                        new
                        {
                            Id = 22,
                            Name = "Epazz",
                            Price = 5m
                        },
                        new
                        {
                            Id = 23,
                            Name = "Vianet",
                            Price = 16m
                        },
                        new
                        {
                            Id = 24,
                            Name = "FlashZero",
                            Price = 35m
                        },
                        new
                        {
                            Id = 25,
                            Name = "Genesis",
                            Price = 98m
                        },
                        new
                        {
                            Id = 26,
                            Name = "InterNAP",
                            Price = 67m
                        },
                        new
                        {
                            Id = 27,
                            Name = "MeetMe",
                            Price = 80m
                        },
                        new
                        {
                            Id = 28,
                            Name = "MeetMe",
                            Price = 90m
                        },
                        new
                        {
                            Id = 29,
                            Name = "Qihoo",
                            Price = 29m
                        });
                });

            modelBuilder.Entity("Domain_.Entities.Order", b =>
                {
                    b.HasOne("Domain_.Entities.Stock", "Stock")
                        .WithMany()
                        .HasForeignKey("StockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stock");
                });
#pragma warning restore 612, 618
        }
    }
}
